version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "simple-ip-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uxzopm8jvt3h"
s3_prefix = "simple-ip-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\" Domain=\"sis.evertsenterprises.com\" HostedZone=\"Z0549346WDXE6Q9VDILT\""
image_repositories = []
